image: lorisleiva/laravel-docker:latest

.init_ssh: &init_ssh |
  eval $(ssh-agent -s)
  echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

.change_file_permissions: &change_file_permissions |
  find . -type f -not -path "./vendor/*" -exec chmod 664 {} \;
  find . -type d -not -path "./vendor/*" -exec chmod 775 {} \;

variables:
  MYSQL_DATABASE: book_me_a_cookie
  MYSQL_ROOT_PASSWORD: secret

composer:
  stage: build

  script:
  - composer install --no-dev --optimize-autoloader --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

  artifacts:
    expire_in: 1 month
    paths:
    - vendor/

  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
    - vendor/

yarn:
  stage: build

  before_script:
  - apk add --no-cache yarn

  cache:
    key: ${CI_COMMIT_REF_SLUG}-yarn
    paths:
    - node_modules/

  script:
    - yarn
    - yarn run prod

  artifacts:
    expire_in: 1 month
    paths:
    - node_modules/
    - public/css/
    - public/js/
    - public/mix-manifest.json

phpunit:
  stage: test

  services:
  - mysql:latest

  dependencies:
  - composer

  before_script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.testing .env
    - php artisan key:generate
    - php artisan migrate

  script:
  - phpunit --coverage-text --colors=never

codestyle:
  stage: test

  dependencies: []

  script:
  - phpcs --standard=PSR2 --extensions=php --ignore=app/Support/helpers.php app

  allow_failure: true

staging:
  stage: deploy

  script:
  - *init_ssh
  - *change_file_permissions
  - php artisan deploy 159.65.201.236 -s upload

  environment:
    name: staging
    url: http://bmac.daveroverts.nl

  only:
  - dev

production:
  stage: deploy

  script:
  - *init_ssh
  - *change_file_permissions
  - php artisan deploy vps1.dutchvacc.nl -s upload

  environment:
    name: production
    url: https://booking.dutchvacc.nl

  when: manual

  only:
  - master
