image: lorisleiva/laravel-docker:latest

composer:
  stage: build

  script:
  - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  - cp .env.example .env
  - php artisan key:generate

  artifacts:
    expire_in: 1 month
    paths:
    - vendor/
    - .env

  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/

yarn:
  stage: build

  cache:
    key: ${CI_COMMIT_REF_SLUG}-yarn
    paths:
    - node_modules/

  script:
    - yarn
    - yarn run prod

  artifacts:
    expire_in: 1 month
    paths:
    - node_modules/
    - public/css/
    - public/js/

phpunit:
  stage: test

  dependencies:
  - composer

  script:
  - phpunit --coverage-text --colors=never

codestyle:
  stage: test

  dependencies: []

  script:
  - phpcs --standard=PSR2 --extensions=php --ignore=app/Support/helpers.php app

staging:
  stage: deploy

  script:
  - wget https://forge.laravel.com/servers/$FORGE_SERVER/sites/$FORGE_SITE/deploy/http?token=$FORGE_TOKEN

  environment:
    name: staging
    url: http://bmac.daveroverts.nl

  only:
    - dev
