image: lorisleiva/laravel-docker:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
- mysql:latest

variables:
  MYSQL_DATABASE: book_me_a_cookie
  MYSQL_ROOT_PASSWORD: secret

composer:
  stage: build

  script:
  - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  - cp .env.testing .env
  - php artisan key:generate
  - php artisan migrate:fresh

  artifacts:
    expire_in: 1 month
    paths:
    - vendor/
    - .env

  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/

yarn:
  stage: build

  before_script:
  - apk add --no-cache yarn

  cache:
    key: ${CI_COMMIT_REF_SLUG}-yarn
    paths:
    - node_modules/

  script:
    - yarn
    - yarn run prod

  artifacts:
    expire_in: 1 month
    paths:
    - node_modules/
    - public/css/
    - public/js/

phpunit:
  stage: test

  dependencies:
  - composer

  script:
  - phpunit --coverage-text --colors=never

codestyle:
  stage: test

  dependencies: []

  script:
  - phpcs --standard=PSR2 --extensions=php --ignore=app/Support/helpers.php app

  allow_failure: true

staging:
  stage: deploy

  script:
  - wget https://forge.laravel.com/servers/$FORGE_SERVER/sites/$FORGE_SITE/deploy/http?token=$FORGE_TOKEN

  environment:
    name: staging
    url: http://bmac.daveroverts.nl

  only:
    - dev
